### ISSUE TITLE
Question: Ignore SubFolders in source

### ISSUE THREAD

**Issue by geetmenon** [KirillOsenkov/ContentSync#3]
We have a case where we want to copy only those files directly under Source folder to Destination folder, and ignore any subfolders under Source folder.  Is there a switch that supports this requirement?

**Comment by KirillOsenkov** [comment]
Yup, `-n` (non-recursive)

**Comment by KirillOsenkov** [comment]
Just published a new release just in case:
https://github.com/KirillOsenkov/ContentSync/releases/download/v1.6/ContentSync.exe

**Comment by geetmenon** [comment]
Thanks!

Could you please include version number in ContentSync.exe. Otherwise it is
difficult to know which version we are on currently.


Thanks
Geetha.

**Comment by KirillOsenkov** [comment]
Will do, thanks. Filed an issue here: https://github.com/KirillOsenkov/ContentSync/issues/4
